from tkinter import *

def add_menubar(editor):
    menubar = Menu(editor, background='#ff8000', foreground='black',
                   activebackground='white', activeforeground='black')
    
    file = Menu(menubar, tearoff=0, foreground='black')
    file.add_command(label="New")
    file.add_command(label="New Window")
    file.add_separator()
    file.add_command(label="Open")
    file.add_command(label="Open Folder")
    file.add_separator()
    file.add_command(label="Save")
    file.add_command(label="Save as")
    file.add_separator()
    file.add_command(label="Open File location")
    file.add_command(label="Reveal in sidebar")
    file.add_command(label="Properties")
    file.add_separator()
    file.add_command(label="Import")
    file.add_command(label="Export")
    file.add_command(label="Print")
    file.add_separator()
    file.add_command(label="Preferences")
    file.add_separator()
    file.add_command(label="Exit", command=editor.quit)
    menubar.add_cascade(label="File", menu=file)

    edit = Menu(menubar, tearoff=0)
    edit.add_command(label="Undo")
    edit.add_command(label="Redo")
    edit.add_separator()
    edit.add_command(label="Cut")
    edit.add_command(label="Copy")
    edit.add_command(label="Paste")
    edit.add_separator()
    edit.add_command(label="Copy as plain text")
    edit.add_command(label="Copy as markdown")
    edit.add_command(label="Copy as html code")
    edit.add_separator()
    edit.add_command(label="Cut")
    edit.add_separator()
    edit.add_command(label="Math Tools")
    edit.add_separator()
    edit.add_command(label="Find and Replace")
    edit.add_separator()
    menubar.add_cascade(label="Edit", menu=edit)

    paragraph = Menu(menubar, tearoff=0)
    paragraph.add_command(label="Undo")
    paragraph.add_command(label="Redo")
    paragraph.add_separator()
    paragraph.add_command(label="Cut")
    paragraph.add_command(label="Copy")
    paragraph.add_command(label="Paste")
    paragraph.add_separator()
    paragraph.add_command(label="Copy as plain text")
    paragraph.add_command(label="Copy as markdown")
    paragraph.add_command(label="Copy as html code")
    paragraph.add_separator()
    paragraph.add_command(label="Cut")
    paragraph.add_separator()
    paragraph.add_command(label="Math Tools")
    paragraph.add_separator()
    paragraph.add_command(label="Find and Replace")
    paragraph.add_separator()
    menubar.add_cascade(label="Paragraph", menu=paragraph)

    help = Menu(menubar, tearoff=0)
    # help.add_command(label="About", command=about)
    menubar.add_cascade(label="Help", menu=help)

    editor.config(menu=menubar)
